### PR TITLE
Bump parquet and arrow deps to version 20

### PR DESCRIPTION
**Pull request by baby-bell**

### CODE REVIEW

**Comment by baby-bell** [comment]
Awaiting workflow approval :)

**Comment by manojkarthick** [comment]
Sorry, I missed this from my notifications. @baby-bell I don't see a workflow approval button anymore (not sure if it's because the PR has been open for some time). Any idea how to revive it? Apologies!

**Comment by baby-bell** [comment]
No worries. I don't see an approval button either, so maybe the issue resolved itself?

**Comment by manojkarthick** [comment]
This PR was superseded by the change from #41

**Pull request closed without merging**
